-- Ayo Suruh - Mobility route endpoints + participant-only live tracking
-- Route jobs use two explicit points: origin/pickup and destination/drop-off.
-- Live GPS points are written only by the assigned Mitra through a guarded RPC.

begin;

-- ---------------------------------------------------------------------------
-- 1. Destination endpoint for route/mobile jobs.
-- Existing address_id/latitude/longitude remain the origin/service point.
-- ---------------------------------------------------------------------------
alter table public.jobs
  add column if not exists destination_address_id uuid references public.addresses(id) on delete set null,
  add column if not exists destination_latitude double precision,
  add column if not exists destination_longitude double precision;

-- Survey kost is a single-site field visit, not an origin -> destination route.
update public.jobs j
set work_mode = 'onsite'
from public.categories c
where c.id = j.category_id
  and lower(c.name) = lower('Survey & Informasi Kost')
  and j.work_mode = 'mobile';

-- Coordinate sanity. NOT VALID keeps historical rows compatible while enforcing
-- the rule for new/changed rows.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'jobs_destination_coordinates_check'
      and conrelid = 'public.jobs'::regclass
  ) then
    alter table public.jobs
      add constraint jobs_destination_coordinates_check
      check (
        (destination_latitude is null and destination_longitude is null)
        or (
          destination_latitude between -90 and 90
          and destination_longitude between -180 and 180
        )
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'jobs_mobile_destination_required_check'
      and conrelid = 'public.jobs'::regclass
  ) then
    alter table public.jobs
      add constraint jobs_mobile_destination_required_check
      check (
        work_mode <> 'mobile'
        or (
          latitude is not null
          and longitude is not null
          and destination_latitude is not null
          and destination_longitude is not null
        )
      ) not valid;
  end if;
end
$$;

create index if not exists idx_jobs_destination_address
  on public.jobs(destination_address_id);

-- ---------------------------------------------------------------------------
-- 2. GPS trail. The client cannot insert directly; only append RPC can write.
-- ---------------------------------------------------------------------------
create table if not exists public.job_live_location_points (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.jobs(id) on delete cascade,
  mitra_id uuid not null references public.users(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_m double precision,
  heading_deg double precision,
  speed_mps double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists idx_job_live_location_points_job_time
  on public.job_live_location_points(job_id, recorded_at desc);

alter table public.job_live_location_points enable row level security;

drop policy if exists "job participants can read live location" on public.job_live_location_points;
create policy "job participants can read live location"
on public.job_live_location_points
for select
to authenticated
using (
  exists (
    select 1
    from public.jobs j
    where j.id = job_live_location_points.job_id
      and j.status = 'on_progress'::public.job_status
      and auth.uid() in (j.customer_id, j.mitra_id)
  )
);

revoke insert, update, delete on public.job_live_location_points from anon, authenticated;
grant select on public.job_live_location_points to authenticated;

create or replace function public.append_job_live_location(
  p_job_id uuid,
  p_latitude double precision,
  p_longitude double precision,
  p_accuracy_m double precision default null,
  p_heading_deg double precision default null,
  p_speed_mps double precision default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mitra_id uuid;
  v_status public.job_status;
  v_work_mode text;
  v_progress public.job_progress_stage;
  v_last public.job_live_location_points%rowtype;
  v_inserted boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Pengguna belum login.';
  end if;

  if p_latitude is null or p_longitude is null
     or p_latitude not between -90 and 90
     or p_longitude not between -180 and 180 then
    raise exception 'Koordinat lokasi tidak valid.';
  end if;

  select j.mitra_id, j.status, j.work_mode, j.progress_stage
  into v_mitra_id, v_status, v_work_mode, v_progress
  from public.jobs j
  where j.id = p_job_id
  for share;

  if not found or v_mitra_id is null or v_mitra_id <> auth.uid() then
    raise exception 'Lokasi hanya dapat dibagikan oleh Mitra yang menangani pekerjaan.';
  end if;

  if v_status <> 'on_progress'::public.job_status
     or coalesce(v_work_mode, '') <> 'mobile'
     or v_progress = 'completion_submitted'::public.job_progress_stage then
    raise exception 'Live tracking hanya aktif saat pekerjaan mobilitas sedang berjalan.';
  end if;

  select * into v_last
  from public.job_live_location_points p
  where p.job_id = p_job_id
  order by p.recorded_at desc
  limit 1;

  -- Keep writes economical: at most about once every 6 seconds, and suppress
  -- near-identical points for 20 seconds. ~0.00003° is roughly a few metres.
  if found then
    if v_last.recorded_at > now() - interval '6 seconds' then
      return false;
    end if;
    if v_last.recorded_at > now() - interval '20 seconds'
       and abs(v_last.latitude - p_latitude) < 0.00003
       and abs(v_last.longitude - p_longitude) < 0.00003 then
      return false;
    end if;
  end if;

  insert into public.job_live_location_points (
    job_id,
    mitra_id,
    latitude,
    longitude,
    accuracy_m,
    heading_deg,
    speed_mps,
    recorded_at
  ) values (
    p_job_id,
    auth.uid(),
    p_latitude,
    p_longitude,
    case when p_accuracy_m is null then null else greatest(p_accuracy_m, 0) end,
    p_heading_deg,
    case when p_speed_mps is null then null else greatest(p_speed_mps, 0) end,
    now()
  );

  v_inserted := true;

  -- Keep only the newest 250 points for the active trail.
  delete from public.job_live_location_points p
  where p.job_id = p_job_id
    and p.id not in (
      select p2.id
      from public.job_live_location_points p2
      where p2.job_id = p_job_id
      order by p2.recorded_at desc
      limit 250
    );

  return v_inserted;
end;
$$;

revoke all on function public.append_job_live_location(
  uuid, double precision, double precision, double precision, double precision, double precision
) from public, anon;
grant execute on function public.append_job_live_location(
  uuid, double precision, double precision, double precision, double precision, double precision
) to authenticated, service_role;

-- Allow Supabase Realtime to broadcast trail changes. Idempotent on rerun.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'job_live_location_points'
  ) then
    alter publication supabase_realtime add table public.job_live_location_points;
  end if;
exception
  when undefined_object then
    null;
end
$$;

-- Periodic cleanup: historical trails are operational data, not permanent user
-- content. Keep up to 30 days and remove finished-job trails after 7 days.
create or replace function public.cleanup_job_live_location_points()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  delete from public.job_live_location_points p
  using public.jobs j
  where j.id = p.job_id
    and (
      p.recorded_at < now() - interval '30 days'
      or (
        j.status in ('completed'::public.job_status, 'cancelled'::public.job_status)
        and p.recorded_at < now() - interval '7 days'
      )
    );
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.cleanup_job_live_location_points() from public, anon, authenticated;
grant execute on function public.cleanup_job_live_location_points() to service_role;

commit;

-- pg_cron is already used by the auto-complete migration. Schedule cleanup if
-- available; deployment still succeeds if Cron is not enabled in this project.
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule(
      'ayo-clean-live-location-trails',
      '17 3 * * *',
      'select public.cleanup_job_live_location_points();'
    );
  end if;
exception
  when undefined_table or invalid_schema_name or undefined_function then
    null;
end
$$;
